a = (int(input("Enter the first number: ")))
b = (int(input("Enter the second number: ")))

print("addition of two numbers is:", a + b)
print("subtraction of two numbers is:", a - b)
print("multiplication of two numbers is:", a * b)
print("division of two numbers is:", a / b)
print("modulus of two numbers is:", a % b)  
print("floor division of two numbers is:", a // b)
print("exponentiation of two numbers is:", a ** b)